apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pac-bio.fullname" . }}
  labels:
    {{- include "pac-bio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pac-bio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pac-bio.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 8243
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
            - name: server
              containerPort: 9243
              protocol: TCP
            - name: api
              containerPort: 9443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
#          volumeMounts:
#            - name: "uploads"
#              mountPath: "/opt/pacbio/smrtlink/userdata/uploads"
#            - name: "jobs-root"
#              mountPath: "/opt/pacbio/smrtlink/userdata/jobs_root.default"
#            - name: "db-datadir"
#              mountPath: "/opt/pacbio/smrtlink/userdata/db_datadir.default"
#      volumes:
#        - name: "uploads"
#          persistentVolumeClaim:
#            claimName: {{ include "pac-bio.fullname" . }}-uploads
#        - name: "jobs-root"
#          persistentVolumeClaim:
#            claimName: {{ include "pac-bio.fullname" . }}-jobs-root
#        - name: "db-datadir"
#          persistentVolumeClaim:
#            claimName: {{ include "pac-bio.fullname" . }}-db-datadir
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
