apiVersion: v1
kind: Service
metadata:
  name: {{ include "pac-bio.fullname" . }}
  labels:
    {{- include "pac-bio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8243
      targetPort: https
      protocol: TCP
      name: https
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
    - port: 9243
      targetPort: server
      protocol: TCP
      name: server
    - port: 9443
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "pac-bio.selectorLabels" . | nindent 4 }}
