name: Docker Build CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-for-git:
    runs-on: ubuntu-latest
    steps:
      - name: Free Up Disk Space
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo apt-get clean
          docker system prune -a -f
          echo "After cleanup:"
          df -h

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set environment variables
        run: |
          echo "BUILD_PROJ=pac-bio" >> $GITHUB_ENV

      - name: Extract branch name
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          echo "Building release version $BRANCH_NAME"
          echo "BUILD_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
        id: extract_branch

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: docker-${{ github.sha }}
          restore-keys: |
            docker-

      - name: Build and push (Main Branch)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:${{ github.ref_name }}
            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:latest

      - name: Build and push (Other Branches)
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/uvarc/${{ env.BUILD_PROJ }}:${{ github.ref_name }}
